Hub token
balancednetwork/balanced-rust-contracts pull request #10
Opened 2023-06-02 07:11 UTC by qwerty0789

2023-06-23 09:05 UTC, ibrizsabin commented on contracts/cw-common/src/data_types.rs
> +        calldata.append(&self.data);
we are appending 5 items to a list of size 4?

2023-06-23 09:07 UTC, ibrizsabin commented on contracts/cw-common/src/hub_token_msg.rs
> +    },
lets not use " _"  infront of struct attributes because it is used to denote unused variables .

2023-06-23 09:07 UTC, ibrizsabin commented on contracts/cw-common/src/hub_token_msg.rs
> +    CrossTransfer {
same here

2023-06-23 09:10 UTC, ibrizsabin commented on contracts/cw-common/src/network_address.rs
> +        &_str[from..to]
no function names should not start with _ . to reduce confusion we can say "str_slice"

2023-06-23 09:11 UTC, ibrizsabin commented on contracts/cw-common/src/x_call_msg.rs
> +}
we may not need this to be passed. lets reduce params wherever posssible. fewer things to remember is better :)

2023-06-23 09:14 UTC, ibrizsabin commented on contracts/token-contracts/cw-hub-bnusd/src/contract.rs
> +        // set self as minter, so we can properly execute mint and burn
name: "HubToken".to_string(),
        symbol: "HUBT".to_string(),
        decimals: 18,
        total_supply: Uint128::zero(),  these things seem to be constant . we can wrap this in a builder method that will return required token with default values and extra params. eg create_token(type:TokenType, ... extra params to override)

2023-06-23 09:16 UTC, ibrizsabin commented on contracts/token-contracts/cw-hub-bnusd/src/contract.rs
> +    }
you can just do "?;" at the end of statement to propagate error like this ==>
let save_token = TOKEN_INFO.save(deps.storage, &data).map_err(ContractError::Std)?;

2023-06-23 09:18 UTC, ibrizsabin commented on contracts/token-contracts/cw-hub-bnusd/src/contract.rs
> +    }
same here. to avoid repeating "map_error"  every where we can wrap storage operation on separate function that will map the errors. its ok for now.

2023-06-23 09:19 UTC, ibrizsabin commented on contracts/token-contracts/cw-hub-bnusd/src/contract.rs
> +    match msg {
unless the imports clashes with other imports ...lets not do imports inside function body. it looks dirty .

2023-06-23 09:21 UTC, ibrizsabin commented on contracts/token-contracts/cw-hub-bnusd/src/error.rs
> +    #[error("Invalid Reply Data")]
duplicate error msg detected.

2023-06-23 09:22 UTC, ibrizsabin commented on contracts/token-contracts/cw-hub-bnusd/src/state.rs
> +pub const X_CALL: Item<String> = Item::new("xCall");
remove comments if we dont need to have them for reference,

2023-06-23 09:25 UTC, ibrizsabin commented on libraries/rust/common/src/rlp/impls.rs
> +            Ok(res)
is this function correct? have we tested this?

2023-06-23 09:29 UTC, ibrizsabin commented on contracts/cw-common/src/data_types.rs
> +    use super::*;
do we really need to enclose it inside module? unless there are type collisions. It will only make imports long and nested.

2023-06-23 09:29 UTC, ibrizsabin commented on contracts/cw-common/src/hub_token_msg.rs
> +
we could have just done use crate::data_types; if we dont enclose it in types mod.

2023-06-23 09:31 UTC, ibrizsabin requested changes
There are few concerns that needs to be addressed here.

2023-06-25 10:21 UTC, qwerty0789 commented on libraries/rust/common/src/rlp/impls.rs
> +            Ok(res)
It was taken from IBC repo, so there is need to test this?

2023-07-04 11:46 UTC, nightowl121 approved these changes

2023-07-11 07:01 UTC, nightowl121 commented on contracts/token-contracts/cw-hub-bnusd/src/contract.rs
> +        let event = Event::new("XCrossTransfer")
Event name should be similar to what's done in transfer method.

2023-07-11 07:01 UTC, nightowl121 commented on contracts/token-contracts/cw-hub-bnusd/src/contract.rs
> +        let event = Event::new("XCrossTransfer")
create a method for events which are created at multiple places with same parameters and name.

2023-09-08 11:12 UTC, nightowl121 approved these changes
Approved

2023-09-08 11:17 UTC, ibrizsabin approved these changes
Looks good

2023-09-08 11:18 UTC, merged