feat: add boilerplate for asset manager contract
balancednetwork/balanced-rust-contracts pull request #12
Opened 2023-06-09 07:24 UTC by nightowl121

2023-07-04 11:25 UTC, nightowl121 reviewed
Please check the review comments @BDEVcoder

2023-07-05 07:31 UTC, nightowl121 commented on contracts/core-contracts/cw-asset-manager/src/state.rs
> +pub const ICON_LOANS_ADDRESS: Item<String> = Item::new("destination_btp_address");
The key is still not changed.

2023-07-05 17:41 UTC, BDEVcoder commented on contracts/core-contracts/cw-asset-manager/src/contract.rs
> +        if DEPOSITS.has(deps.storage, (&info.sender, &token)) {
current deposit balance for token of the user has been checked

2023-07-05 17:43 UTC, BDEVcoder commented on contracts/core-contracts/cw-asset-manager/src/contract.rs
> +        let token_address = Addr::unchecked(token_address);
i have used address reference for states therefore use unchecked addr for the transfer token fun()

2023-09-13 06:13 UTC, AntonAndell requested changes
Some minor changes could be made, otherwise it looks good.
Also RLP lib has to be changed to the one in IBC integrations to keep consistent with JAVA rlp

2023-09-13 06:13 UTC, AntonAndell commented on contracts/core-contracts/cw-asset-manager/src/contract.rs
> +            let depositor = NetworkAddress::new(nid.as_str(), info.sender.as_str());
Does not need to be converted to network address can be kept as regular address

2023-09-13 06:49 UTC, nightowl121 commented on contracts/core-contracts/cw-asset-manager/src/constants.rs
> +pub const SUCCESS_REPLY_MSG: u64 = 1;
The id is supplied as a placeholder, it's not received back.

2023-09-13 06:51 UTC, nightowl121 commented on contracts/core-contracts/cw-asset-manager/src/contract.rs
> +            let depositor = NetworkAddress::new(nid.as_str(), info.sender.as_str());
Agree, will convert it to native archway address.

2023-09-14 06:39 UTC, AntonAndell approved these changes
LGTM, lets get this in and do smaller Upgrade PRs :+1:

2023-09-14 06:43 UTC, merged