feature: Implement balanced xcall manager
balancednetwork/balanced-rust-contracts pull request #55
Opened 2023-11-13 13:47 UTC by AntonAndell

2024-01-24 10:44 UTC, ibrizsabin commented on contracts/core-contracts/cw-xcall-manager/src/contract.rs
> +
we can directly compare 2 vec<String> rust supports equality operator for vec if the element in vec implements `Eq` trait. I have tested it with a unit test as well so we can just do &a==&b.

2024-01-24 11:44 UTC, ibrizsabin commented on contracts/core-contracts/cw-xcall-manager/README.md
> +Please replace this README file with information about your specific project. You can keep
maybe update the readme only to include relevant info to the project

2024-01-24 11:48 UTC, ibrizsabin commented on contracts/cw-common/src/helpers.rs
> +
we can just do `VerifyProtocols{protocols: protocols.unwrap_or_default()}`

2024-01-24 11:50 UTC, ibrizsabin commented on contracts/cw-common/src/helpers.rs
> +
or we can just revert if protocols are empty?

2024-01-24 11:51 UTC, ibrizsabin requested changes
few refactoring concerns

2024-01-31 14:13 UTC, AntonAndell commented on contracts/core-contracts/cw-xcall-manager/README.md
> +Please replace this README file with information about your specific project. You can keep
Lets remove this for now, we can update the most outer one instead later

2024-01-31 14:17 UTC, AntonAndell commented on contracts/core-contracts/cw-xcall-manager/src/contract.rs
> +
This fails if the protocols where not specified in the same order, which is important for the proposed removals

2024-01-31 14:18 UTC, AntonAndell commented on contracts/cw-common/src/helpers.rs
> +
And default just gives !vec[]? 
We can revert since empty just means default for xCall

2024-01-31 15:12 UTC, ibrizsabin commented on contracts/cw-common/src/helpers.rs
> +
ya default will give empty vec.

2024-02-01 06:42 UTC, ibrizsabin commented on contracts/core-contracts/cw-xcall-manager/src/contract.rs
> +
oh ya . the arrays need to be identical which is not ideal for our case. ironically i noticed the same issue in solidity where order becomes important but it shouldnt be.

2024-02-01 06:43 UTC, ibrizsabin approved these changes

2024-02-01 07:38 UTC, merged